version: "3.7"

services:
  app:
    image: node:16.13.1
    command: npm run dev
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: rust

  mysql:
    image: mysql:5.7
    volumes:
      - rust-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: rust

volumes:
  rust-mysql-data: