version: "3.7"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: npm run start
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: rust
      REDIS_HOST: redis
      REDIS_URL: redis://cache
      REDIS_PORT: 6379

  mysql:
    image: mysql:5.7
    volumes:
      - rust-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: rust
  
  redis:
    image: redis:alpine
    container_name: cache
    ports:
      - 6379:6379

volumes:
  rust-mysql-data: